version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: snippetbox-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "123"
      MYSQL_DATABASE: "snippetbox"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p123"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7.2
    container_name: snippetbox-redis
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", ""]

volumes:
  db_data: 