apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "snippetbox.fullname" . }}
data:
  config.toml: |-
    {{- include "common.tplvalues.render" ( dict "value" .Values.configuration "context" $ ) | nindent 4 }}