[server]
port = 4000
[database]
host = "db"
port = 3306
user = "root"
password = "123"
name = "snippetbox"
[i18n]
lang = "en"
[redis]
host = "redis"
port = 6379
password = ""
authKey = "vP93NGmluBFBHwUk+UX2vh53S/IrvQ0bAe09ZS5JCeY="
encryptionKey = "RgSJjzcbxD3JXKPzUzy6LHlpfCsbngFVxFF0r7y+GBw="